### ISSUE TITLE
Dummy feature to check location on localhost

### ISSUE THREAD

**Issue by johnnyAnd** [RestComm/gmlc#56]
I am configuring OPENGMLC on my localhost , when I do /restomm with an msisdn , it shows empty response which is ok, there needs to be some simulator or dummy msisdn that I can pass to it and it can send me response.

Thanks 
#53

**Comment by deruelle** [comment]
@JohnTet do you want to contribute that example ?

**Comment by johnnyAnd** [comment]
@deruelle  I would love to ofcourse but I am struggling myself to run it on localhost.

**Comment by angrygreenfrogs** [comment]
@JohnTet Recommend to check out the updated README file here: https://github.com/RestComm/gmlc/blob/issue45/README.md

That may help if you're having any install/run problems, and has details about how to setup a dev environment.

In general also you'll see a little bit of a better immediate test response (even though it'll be an error) if you send a MLP POST request instead of a GET

**Comment by FerUy** [comment]
@JohnTet I'm back :)

I'm reviewing @angrygreenfrogs PR and will provide further feedback on this hopefully today. Thanks!

**Comment by angrygreenfrogs** [comment]
@JohnTet @FerUy Oh, on this subject, I should say there's already a little bit of test code in the GMLC for this.

It'd be nicer if there was a "dummy" mode configuration variable to turn it on... but in any case you can set this to true in core/slee/services/sbbs/src/main/java/org/mobicents/gmlc/slee/MobileCoreNetworkInterfaceSbb.java 

```
private boolean useFakeLocation = false;
```

And it'll return a fake location from POST or GET rather than trying to do a real request.

**Comment by johnnyAnd** [comment]
@angrygreenfrogs and then I have to compile it from scratch ? creating snapshot etc. just asking ..

**Comment by Vanit** [comment]
Maybe an easy solution would be for there to be a dummy mobile number that will always return a successful fake location?

**Comment by deruelle** [comment]
@Monix that's an option. We need to make sure it's a non valid mobile number or enable that only when fake is enabled through configuration

**Comment by Vanit** [comment]
@deruelle Maybe a fictional 555 number?

**Comment by deruelle** [comment]
yeah sounds good to me
