### ISSUE TITLE
Dialog is never released

### ISSUE THREAD

**Issue by jaimecasero** [RestComm/gmlc#84]
https://github.com/RestComm/gmlc/blob/master/core/slee/services/sbbs/src/main/java/org/mobicents/gmlc/slee/MobileCoreNetworkInterfaceSbb.java#L330

after receiveng map response we should close dialog, by invoking dialog.release.

This will prevent to receive the dialogtimeout event, and free resources much previouslly

**Comment by FerUy** [comment]
@jaimecasero just added the dialog release. Let's see how it impacts the automated performance test before resolving #83.

**Comment by FerUy** [comment]
Consistently with GMLC-Performance-GetLoc/78, this is closed

**Comment by vetss** [comment]
@jaimecasero @FerUy 

You do not need to add "close() / release()" staff to onAnyTimeInterrogationResponse() because a dialog is closed / released by a peer (a peer is sending TC-END message that just close / release this dialog)

The most probaly reason of "dialogtimeout event" - if you have too high message load then SCTP channel can not pass all load, then messages came to a peer with delays and when this delay increase invoke / dialog timeout margine then you can see many dialog timeout event in logs.
Try to decrease a message load level.

**Comment by FerUy** [comment]
@vetss thanks!
You're right, working on it

**Comment by FerUy** [comment]
Now MAP ATI is working as it expected (TC-BEG for request, TC-END for response) and dialog properly released. Local tests between posterior build 1.0.65 and MAP server stub are also OK as for the attached trace. MAP serverStub log looks fine in this regard as for http://ci.telestax.com/job/GMLC-Performance-GetLoc/85/artifact/results/serverStub.log (i.e. there are no more dialog timeouts, dialogs are released for each MAP ATI request for the whole test).

**Comment by FerUy** [comment]
Just for the record, http://ci.telestax.com/job/GMLC-Performance-GetLoc/90/ confirms this issue was properly closed as for it concern.
